[package]
name = "chaos"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.11.6"
getrandom = { version = "0.2.12", features = ["custom"] }
